import { Article, Paper, TelemetryData } from './types';

export const defaultFeaturedArticle: Article = {
  id: "case-study-104",
  slug: "microservices-bad-oop-at-scale",
  title: "Your Microservices Architecture is Just Bad OOP at Scale",
  category: "SYSTEM DISSECTION // CASE STUDY #104",
  author: "DR. ALAN VECTOR",
  topic: "DISTRIBUTED SYSTEMS",
  readTime: "9 MIN",
  lead: "By trading in-memory function invocations for uncompressed HTTP REST hops across fifteen internal services, modern engineering teams have managed to reinvent object encapsulation while simultaneously adding 600ms of tail latency.",
  body: [
    "We took an audit of a standard e-commerce transaction pipeline operating across 18 distinct microservices. The claim was 'independent scalability.' The empirical reality was an interconnected graph of synchronous blocking calls prone to cascading failure modes and astronomical network serialization overhead.",
    "In next week's issue, we break down the assembly generated by popular ORM frameworks and explain why your database queries are generating four orders of magnitude more pointer allocations than necessary."
  ],
  pullquote: "An algorithm is a strategy to reach a goal under constraints. Distributing state across 20 network boundaries when your data fits in single-socket L3 cache is not engineering—it is negligence.",
  benchmarks: [
    {
      architecture: "Unified In-Memory State Machine",
      p50: "0.42 ms",
      p99: "1.18 ms",
      memory: "128 MB"
    },
    {
      architecture: "Isolated Domain Modules (Monolith)",
      p50: "1.15 ms",
      p99: "3.40 ms",
      memory: "210 MB"
    },
    {
      architecture: "18-Node HTTP/JSON Microservices",
      p50: "148.00 ms",
      p99: "840.20 ms",
      memory: "14.2 GB"
    }
  ],
  flameGraphHeader: "> FLAME_GRAPH_AUDIT: CHECKOUT_TRACE_P99",
  flameGraphLines: [
    "[0.00ms] HTTP POST /checkout/commit",
    "  ├── [42.10ms] JSON_SERIALIZE (OrderPayload, 4.2KB)",
    "  ├── [98.40ms] TLS_HANDSHAKE + DNS (Auth-Service.internal)",
    "  ├── [120.30ms] DB_POOL_ACQUIRE_TIMEOUT (Lock contention on user_token)",
    "  └── [579.40ms] CASCADING_RETRY_STORM: Payment-Gateway Node 4 failed (ALERT)"
  ],
  publishedAt: "2026-08-23",
  isFeatured: true
};

export const defaultPapers: Paper[] = [
  {
    id: "paper-00841",
    title: "Aether-Net: Deterministic Consensus in Asymmetric Latency Topologies",
    doi: "10.1978/DCS.00841",
    pages: 14
  },
  {
    id: "paper-00839",
    title: "Evaluating Cache Locality vs Big O Complexity in Modern Silicon",
    doi: "10.1978/DCS.00839",
    pages: 22
  },
  {
    id: "paper-00834",
    title: "Zero-Overhead Memory Compaction for Remote Terminals",
    doi: "10.1978/DCS.00834",
    pages: 18
  }
];

export const defaultTelemetry: TelemetryData = {
  node: "Nimbus-1 Cluster 01",
  runtime: "Native Aether-Link",
  allocatedMem: "2.14 MB / UNBOUND",
  cpuEfficiency: "99.4%",
  invocationOverhead: "0.0002ms",
  status: "NO REDUNDANT HOPS"
};
