import { Article, Paper, TelemetryData } from './types';

export const defaultFeaturedArticle: Article = {
  id: "case-study-104",
  slug: "microservices-bad-oop-at-scale",
  title: "Your Microservices Architecture is Just Bad OOP at Scale",
  category: "SYSTEM DISSECTION // CASE STUDY #104",
  author: "DR. ALAN VECTOR",
  topic: "DISTRIBUTED SYSTEMS",
  readTime: "9 MIN",
  lead: "By trading in-memory function invocations for uncompressed HTTP REST hops across fifteen internal services, modern engineering teams have managed to reinvent object encapsulation while simultaneously adding 600ms of tail latency.",
  body: [
    "We took an audit of a standard e-commerce transaction pipeline operating across 18 distinct microservices. The claim was 'independent scalability.' The empirical reality was an interconnected graph of synchronous blocking calls prone to cascading failure modes and astronomical network serialization overhead.",
    "In next week's issue, we break down the assembly generated by popular ORM frameworks and explain why your database queries are generating four orders of magnitude more pointer allocations than necessary."
  ],
  markdownContent: `
### The Illusion of Isolation

Consider the theoretical premise of distributed services: each bounded context manages its own transactional boundary. However, in practice, network boundaries do not isolate invariants—they merely transform compile-time type errors into runtime HTTP 504 timeouts.

\`\`\`rust
// Zero-overhead in-memory dispatch vs 600ms RPC
pub struct TransactionPipeline {
    ledger: MemoryLedger,
    auth: FastTokenValidator,
}

impl TransactionPipeline {
    #[inline(always)]
    pub fn commit(&mut self, tx: &OrderPayload) -> Result<Receipt, LedgerError> {
        self.auth.verify(&tx.token)?;
        self.ledger.execute_atomic(tx)
    }
}
\`\`\`

### Latency Compounding Under Distributed Topologies

When service dependencies form a linear graph of depth $k$, with each node exhibiting independent latency distribution $\\mathcal{L}_i \\sim \\text{LogNormal}(\\mu_i, \\sigma_i^2)$, the aggregate tail latency $P_{99}$ is strictly super-additive:

$$P_{99}(\\text{Total}) \\gg \\sum_{i=1}^k P_{50}(\\mathcal{L}_i) + \\max_{1 \\le i \\le k} \\Delta_{\\text{network}}$$

By trading in-memory cache coherence for uncompressed JSON payloads over TLS, systems incur a 4-order-of-magnitude tax on cache line utilization.
`,
  pullquote: "An algorithm is a strategy to reach a goal under constraints. Distributing state across 20 network boundaries when your data fits in single-socket L3 cache is not engineering—it is negligence.",
  benchmarks: [
    {
      architecture: "Unified In-Memory State Machine",
      p50: "0.42 ms",
      p99: "1.18 ms",
      memory: "128 MB"
    },
    {
      architecture: "Isolated Domain Modules (Monolith)",
      p50: "1.15 ms",
      p99: "3.40 ms",
      memory: "210 MB"
    },
    {
      architecture: "18-Node HTTP/JSON Microservices",
      p50: "148.00 ms",
      p99: "840.20 ms",
      memory: "14.2 GB"
    }
  ],
  flameGraphHeader: "> FLAME_GRAPH_AUDIT: CHECKOUT_TRACE_P99",
  flameGraphLines: [
    "[0.00ms] HTTP POST /checkout/commit",
    "  ├── [42.10ms] JSON_SERIALIZE (OrderPayload, 4.2KB)",
    "  ├── [98.40ms] TLS_HANDSHAKE + DNS (Auth-Service.internal)",
    "  ├── [120.30ms] DB_POOL_ACQUIRE_TIMEOUT (Lock contention on user_token)",
    "  └── [579.40ms] CASCADING_RETRY_STORM: Payment-Gateway Node 4 failed (ALERT)"
  ],
  publishedAt: "2026-08-23",
  isFeatured: true
};

export const defaultPapers: Paper[] = [
  {
    id: "paper-00841",
    title: "Aether-Net: Deterministic Consensus in Asymmetric Latency Topologies",
    doi: "10.1978/DCS.00841",
    authors: "Dr. Alan Vector, Elena Vance",
    year: 2026,
    pages: 14,
    category: "DISTRIBUTED CONSENSUS",
    abstract: "We present Aether-Net, a deterministic Byzantine fault-tolerant consensus protocol optimized for networks with severe latency asymmetry. By decoupling quorum validation from state replication, we demonstrate sub-5ms finality across trans-continental nodes without speculative execution.",
    bibtex: `@article{vector2026aether,
  author    = {Vector, Alan and Vance, Elena},
  title     = {Aether-Net: Deterministic Consensus in Asymmetric Latency Topologies},
  journal   = {Distant CS Proceedings on Computational Systems},
  volume    = {78},
  pages     = {1--14},
  year      = {2026},
  doi       = {10.1978/DCS.00841}
}`
  },
  {
    id: "paper-00839",
    title: "Evaluating Cache Locality vs Big O Complexity in Modern Silicon",
    doi: "10.1978/DCS.00839",
    authors: "Marcus Sterling, Dr. Alan Vector",
    year: 2026,
    pages: 22,
    category: "COMPUTER ARCHITECTURE",
    abstract: "Modern superscalar CPUs with 3-level cache hierarchies fundamentally alter algorithmic performance characteristics. We benchmark continuous linear arrays against balanced AVL trees across N=10^6 elements, proving O(N) sequential scans outperform O(log N) pointer-chasing algorithms due to hardware prefetchers.",
    bibtex: `@article{sterling2026cache,
  author    = {Sterling, Marcus and Vector, Alan},
  title     = {Evaluating Cache Locality vs Big O Complexity in Modern Silicon},
  journal   = {Distant CS Proceedings on Computational Systems},
  volume    = {78},
  pages     = {15--36},
  year      = {2026},
  doi       = {10.1978/DCS.00839}
}`
  },
  {
    id: "paper-00834",
    title: "Zero-Overhead Memory Compaction for Remote Terminals",
    doi: "10.1978/DCS.00834",
    authors: "Dr. Maya Lin",
    year: 2025,
    pages: 18,
    category: "SYSTEMS OPTIMIZATION",
    abstract: "Remote and embedded compute nodes frequently suffer from virtual memory fragmentation under persistent buffer allocations. We present an in-place generational compactor operating strictly during idle micro-quanta with zero pause times.",
    bibtex: `@article{lin2025memory,
  author    = {Lin, Maya},
  title     = {Zero-Overhead Memory Compaction for Remote Terminals},
  journal   = {Distant CS Proceedings on Computational Systems},
  volume    = {77},
  pages     = {40--58},
  year      = {2025},
  doi       = {10.1978/DCS.00834}
}`
  }
];

export const defaultTelemetry: TelemetryData = {
  node: "Nimbus-1 Cluster 01",
  runtime: "Native Aether-Link",
  allocatedMem: "2.14 MB / UNBOUND",
  cpuEfficiency: "99.4%",
  invocationOverhead: "0.0002ms",
  status: "NO REDUNDANT HOPS"
};
